COMMAND:
  - namekox_sqlalchemy.cli.subcmd.migration:Alembic
DATABASE:
  ping: mysql+pymysql://${MYSQL_USER:root}:${MYSQL_PASS:toor}@${MYSQL_HOST:127.0.0.1}:${MYSQL_PORT:3306}/ping_service?charset=utf8
